openapi: 3.0.3

info:
    title: JWT Demo App
    version: 1.0.0
    description: A Express Server For Login and Sign Up using JWT
    contact:
        url: https://github.com/enthr

servers:
    - url: http://localhost:5000/api
      description: Development server
    - url: https://express-jwt-demo.onrender.com/api
      description: Production server

components:
    securitySchemes:
        cookieAuth:
            type: apiKey
            in: cookie
            name: token

paths:
    /auth/login:
        post:
            summary: Login to the application
            description: Login to the application
            consumes:
                - application/json
            produces:
                - application/json
            requestBody:
                description: Login to the application
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    description: Email of the user
                                    example: saitama@onepunch.man
                                password:
                                    type: string
                                    description: Password of the user
                                    example: Saitama@one123
                            required:
                                - email
                                - password
            responses:
                200:
                    description: Returns an Object with success, token and user
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        description: Status of the request
                                        example: true
                                    token:
                                        type: string
                                        description: JWT Token
                                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhaXRhbXNAb25lcHVuY2gubWFuIiwiaWF0IjoxNj
                                    user:
                                        type: object
                                        properties:
                                            _id:
                                                type: string
                                                description: Id of the user
                                                example: 5f9e8b5b1c9d440000f3b1a0
                                            name:
                                                type: string
                                                description: Name of the user
                                                example: Saitama
                                            email:
                                                type: string
                                                description: Email of the user
                                                example: saitama@onepunch.man
                                            createdAt:
                                                type: string
                                                description: Created At of the user
                                                example: 2020-11-01T16:00:00.000Z
                                            updatedAt:
                                                type: string
                                                description: Updated At of the user
                                                example: 2020-11-01T16:00:00.000Z
    /auth/logout:
        get:
            summary: Logout from the application
            description: Logout from the application
            security:
                - cookieAuth: []
            parameters:
                - in: header
                  name: token
                  schema:
                      type: string
                  required: true
                  description: JWT Token
            responses:
                200:
                    description: Returns an Object with success and message
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        description: Status of the request
                                        example: true
                                    message:
                                        type: string
                                        description: Message of the request
                                        example: Logged Out
    /auth/signup:
        post:
            summary: Sign Up to the application
            description: Sign Up to the application
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    description: Name of the user
                                    example: Saitama
                                email:
                                    type: string
                                    description: Email of the user
                                    example: saitama@onepunch.man
                                password:
                                    type: string
                                    description: Password of the user
                                    example: Saitama@one123
                            required:
                                - name
                                - email
                                - password
            responses:
                200:
                    description: Returns an Object with success, token and user
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        description: Status of the request
                                        example: true
                                    token:
                                        type: string
                                        description: JWT Token
                                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhaXRhbXNAb25lcHVuY2gubWFuIiwiaWF0IjoxNj
                                    user:
                                        type: object
                                        properties:
                                            _id:
                                                type: string
                                                description: Id of the user
                                                example: 5f9e8b5b1c9d440000f3b1a0
                                            name:
                                                type: string
                                                description: Name of the user
                                                example: Saitama
                                            email:
                                                type: string
                                                description: Email of the user
                                                example: saitama@onepunch.man
                                            createdAt:
                                                type: string
                                                description: Created At of the user
                                                example: 2020-11-01T16:00:00.000Z
                                            updatedAt:
                                                type: string
                                                description: Updated At of the user
                                                example: 2020-11-01T16:00:00.000Z